### ISSUE TITLE
Delete requests from other app

### ISSUE THREAD

**Issue by dd-iuonac** [slyapustin/django-s3-like-storage#12]
Use case: One app is uploads files to a bucket. At some point there is a need to delete some of the files. Even though they got deleted on the app side they don't get deleted from the bucket. 

I tried something  like this but didn't worked:
  
    @receiver(post_delete, sender=Song)    

    def delete_audio_file(sender, instance, **kwargs):   

          instance.audio.delete(False)

The requests are sent, but the files are not deleted from the bucket.

How could I implement delete requests to work? Could you give some examples?

![Screenshot 2022-06-30 154912](https://user-images.githubusercontent.com/45289603/176680880-0a54b371-e02b-4083-b25f-56552a5f2635.jpg)

**Comment by slyapustin** [comment]
Hey @dd-iuonac , 
Unfortunately, that feature is not implemented. 
But, I think that will be relatively simple to implement - you just need to handle the DELETE request here: https://github.com/slyapustin/django-s3-like-storage/blob/b27e2edf48c31620cf488db2cd379b71a3c82129/storage/views.py#L35

Feel free to create PR for that.
